name: IBM Cloud Auto Restart
 
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '35 21 * * 4'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        pwd
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
      run: |
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud target --cf
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud cf install
        cd v2ray-cloudfoundry
        sed -i "s/GetStartedGo/${{ secrets.IBM_APP_NAME }}/g"  manifest-ibm.yml
        cat manifest-ibm.yml
        chmod +x *
#        rm -rf manifest-ibm.yml
#        cat > manifest-ibm.yml << EOF
#        applications:
#        - path: .
#          name: "$IBM_APP_NAME"
#          memory: 256M
#          random-route: true
#        EOF
#        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud cf push
#     - name: Restart IBM Cloud
#       env:
#         IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
#       run: |
#         ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME"
 
